#! /bin/dash

FIRST_DESK=I
REMAINING_DESKS='II III IV V VI VII VIII IX X'
bspc desktop Desktop01 -n $FIRST_DESK
bspc monitor -a $REMAINING_DESKS
bspc monitor -p 24 0 0 0

# bspc monitor Monitor01 -n X
# bspc desktop Desktop01 -n Y
# bspc monitor -A Alpha 1920x720+0+0
# bspc monitor -A Beta 1560x360+0+720
# bspc monitor -A Gamma 360x360+1560+720
# bspc monitor Alpha -p 24 0 0 0
# bspc desktop Desktop02 -n One
# bspc monitor Alpha -a Two Three
# bspc desktop Desktop03 -n Four
# bspc monitor Beta -a Five Six Seven Eight
# bspc desktop Desktop04 -n Nine
# bspc monitor Gamma -a Ten
# bspc monitor -f Alpha

bspc rule -a Gimp -d Eight --floating --follow
bspc rule -a Inkscape -d Seven --floating --follow
bspc rule -a fontforge -d Six --floating --follow
bspc rule -a Gifview --floating

bspc config border_width      2
bspc config window_gap       12
bspc config split_ratio       0.52

bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config apply_floating_atom    true
bspc config history_aware_focus    true
bspc config focus_follows_pointer  false
bspc config adaptative_raise       false

if [ -e "$BSPWM_TREE" ] ; then
    bspc restore -T "$BSPWM_TREE"
    rm "$BSPWM_TREE"
else
    bspc control --adopt-orphans
fi

if [ -e "$BSPWM_HISTORY" ] ; then
    bspc restore -H "$BSPWM_HISTORY"
    rm "$BSPWM_HISTORY"
fi

updatethm
compton -b
