#! /bin/dash

bspc desktop ^1 -n I
bspc monitor -a II III IV V VI VII VIII IX X
bspc config -m ^1 top_padding $PANEL_HEIGHT

# bspc monitor ^1 -n Y
# bspc monitor -A ALPHA 1920x720+0+0
# bspc monitor -A BETA 1560x360+0+720
# bspc monitor -A GAMMA 360x360+1560+720
# bspc desktop ^1 -n Z
# bspc desktop ^2 -n I
# bspc desktop ^3 -n V
# bspc desktop ^4 -n VIII
# bspc monitor ALPHA -a II III IV
# bspc monitor BETA -a VI VII
# bspc monitor GAMMA -a IX X
# bspc config -m ALPHA top_padding $PANEL_HEIGHT
# bspc monitor -f ALPHA

bspc rule -a Gimp -d ^8 --follow --floating
bspc rule -a Inkscape -d ^7 --follow --floating
bspc rule -a fontforge -d ^6 --follow --floating
bspc rule -a Gifview --floating

bspc config window_gap       12
bspc config border_width      2
bspc config split_ratio       0.52

bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config apply_floating_atom    true
bspc config history_aware_focus    true

if [ -e "$BSPWM_TREE" ] ; then
    bspc restore -T "$BSPWM_TREE"
    rm "$BSPWM_TREE"
fi

if [ -e "$BSPWM_HISTORY" ] ; then
    bspc restore -H "$BSPWM_HISTORY"
    rm "$BSPWM_HISTORY"
fi

if updatethm ; then
    reloadthm
else
    bspwm_colors
    reloadwallpaper
    reloadpanel
fi

compton -b
