#! /bin/dash

bspc desktop ^1 -n I
bspc monitor -a II III IV V VI VII VIII IX X
bspc config top_padding $PANEL_HEIGHT

# bspc monitor -A ALPHA 1920x720+0+0
# bspc monitor -A BETA 1560x360+0+720
# bspc monitor -A GAMMA 360x360+1560+720
# bspc monitor -R MONITOR01
# bspc desktop ^1 -n I
# bspc desktop ^2 -n V
# bspc desktop ^3 -n VIII
# bspc monitor ALPHA -a II III IV
# bspc monitor BETA -a VI VII
# bspc monitor GAMMA -a IX X
# bspc config -m ALPHA top_padding $PANEL_HEIGHT

bspc rule -a Gimp -d ^8 --follow --floating
bspc rule -a Inkscape -d ^7 --follow --floating
bspc rule -a fontforge -d ^6 --follow --floating
bspc rule -a Gifview --floating

bspc config window_gap       12
bspc config border_width      2
bspc config split_ratio       0.52

bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config apply_floating_atom    true
bspc config history_aware_focus    true

if [ -e "$BSPWM_TREE" ] ; then
    bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
    rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi

if updatethm ; then
    reloadthm
else
    bspwm_colors
    reloadwallpaper
    reloadpanel
fi

compton -b
