set guioptions-=m
set guioptions-=t
set guioptions-=T
set guioptions-=r
set guioptions-=R
set guioptions-=b
set guioptions-=l
set guioptions-=L
set guicursor=a:blinkon0
set guifont=monospace\ 14px
set keywordprg=kwprg_gvim
