set guioptions-=m
set guioptions-=t
set guioptions-=T
set guioptions-=r
set guioptions-=R
set guioptions-=b
set guioptions-=l
set guioptions-=L
set guicursor=a:blinkon0
set guifont=Fira\ Mono:h16
" set keywordprg=kwprg_gvim
