#! /bin/dash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

hc keyunbind --all

Mod=Mod4
hc keybind $Mod-Alt-Escape quit
hc keybind $Mod-Escape reload
hc keybind $Mod-w close

DEFAULT_TAG='one'
TAG_NAMES="$DEFAULT_TAG two three four five six seven eight nine"
tag_key=1

hc rename default "$DEFAULT_TAG"

for tag_name in $TAG_NAMES ; do
    hc add "$tag_name"
    hc keybind "$Mod-$tag_key" use "$tag_name"
    hc keybind "$Mod-Shift-$tag_key" move "$tag_name"
    tag_key=$(((tag_key + 1) % 10))
    hc load "$tag_name" '(clients grid:0)'
done

hc keybind $Mod-r remove
hc keybind $Mod-u split vertical 0.5
hc keybind $Mod-o split horizontal 0.5
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
hc keybind $Mod-v set_layout vertical
hc keybind $Mod-n set_layout horizontal
hc keybind $Mod-m set_layout max
hc keybind $Mod-Return set_layout max
hc keybind $Mod-g set_layout grid
hc keybind $Mod-0 load '(clients grid:0)'
hc keybind $Mod-grave rotate

RESIZESTEP=0.03

hc keybind $Mod-Control-h resize left  +$RESIZESTEP
hc keybind $Mod-Control-j resize down  +$RESIZESTEP
hc keybind $Mod-Control-k resize up    +$RESIZESTEP
hc keybind $Mod-Control-l resize right +$RESIZESTEP

hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

hc keybind $Mod-Tab         cycle_all --skip-invisible +1
hc keybind $Mod-Shift-Tab   cycle_all --skip-invisible -1
hc keybind $Mod-c cycle +1
hc keybind $Mod-Shift-c cycle -1
hc keybind $Mod-h focus left
hc keybind $Mod-j focus down
hc keybind $Mod-k focus up
hc keybind $Mod-l focus right
hc keybind $Mod-Alt-h focus -e left
hc keybind $Mod-Alt-j focus -e down
hc keybind $Mod-Alt-k focus -e up
hc keybind $Mod-Alt-l focus -e right
hc keybind $Mod-Shift-h shift left
hc keybind $Mod-Shift-j shift down
hc keybind $Mod-Shift-k shift up
hc keybind $Mod-Shift-l shift right
hc keybind $Mod-Alt-Shift-h shift -e left
hc keybind $Mod-Alt-Shift-j shift -e down
hc keybind $Mod-Alt-Shift-k shift -e up
hc keybind $Mod-Alt-Shift-l shift -e right

hc keybind $Mod-bracketleft use_index -1
hc keybind $Mod-bracketright use_index +1
hc keybind $Mod-braceleft cycle_monitor -1
hc keybind $Mod-braceright cycle_monitor +1

hc set raise_on_focus        1
hc set always_show_frame     0
hc set default_frame_layout  3
hc set gapless_grid          1
hc set smart_frame_surroundings 1
hc set smart_window_surroundings 1
hc set frame_gap             0
hc set window_gap            2
hc set frame_border_width    4
hc set window_border_width   4
hc set window_border_inner_width   3
hc set frame_border_inner_width   3
# hc set frame_normal_opacity  0
# hc set frame_active_opacity  0

hc unrule -F
hc rule focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule class=Dwb tag=two
hc rule instance=mutt tag=three
hc rule instance=slrn tag=three
hc rule class=Xscreensaver-demo pseudotile=on
hc rule instance=ncmpcpp tag=nine
hc rule class=Inkscape title~'^Export Bitmap' pseudotile=on
hc rule class=Audacity title='Frequency Analysis' pseudotile=off
hc rule class=fontforge tag=seven
hc floating seven on
hc rule class=Gimp tag=eight
hc load eight '
(split horizontal:0.850000:0
  (split horizontal:0.200000:1
    (clients vertical:0)
    (clients grid:0))
  (clients vertical:0))
'
hc rule class=Gimp tag=eight index=01 pseudotile=on
hc rule class=Gimp windowrole~'gimp-(image-window|toolbox|dock)' pseudotile=off
hc rule class=Gimp windowrole=gimp-toolbox focus=off index=00
hc rule class=Gimp windowrole=gimp-dock focus=off index=1

hc unlock

updatethm
# reloadwallpaper
