#! /bin/dash

bspc set normal_border_color "{{bg_dip}}"
bspc set active_border_color "{{fg_comment}}"
bspc set locked_border_color "{{magenta_comment}}"
bspc set inner_border_color "{{background}}"
bspc set outer_border_color "{{background}}"
