#! /bin/dash

printf "\033]P032312E"   # black
printf "\033]P87E7F89"   # darkgrey

printf "\033]P7A4A6B1"   # lightgrey
printf "\033]PFCECFDB" # white

printf "\033]P63F3E3B"      # darkcyan
printf "\033]PE4CB6C3"         # cyan

printf "\033]P1CF9B73"       # darkred
printf "\033]P9DD928A"          # red

printf "\033]P2DE8FA8"         # darkgreen
printf "\033]PA75B487"        # green

printf "\033]P3B19DDA"       # darkyellow
printf "\033]PBB6A56A"       # yellow

printf "\033]P497AE71"       # darkblue
printf "\033]PC62B1D9"        # blue

printf "\033]P557B7A5"         # darkmagenta
printf "\033]PDCE94C5"      # magenta

clear