#! /bin/dash

printf "\033]P032312E"   # black
printf "\033]P87E7F89"   # darkgrey

printf "\033]P7A4A6B1"   # lightgrey
printf "\033]PFCECFDB" # white

printf "\033]P63F3E3B"      # darkcyan
printf "\033]PE5EC6D4"         # cyan

printf "\033]P1E0AB83"       # darkred
printf "\033]P9EFA29A"          # red

printf "\033]P2EF9FB8"         # darkgreen
printf "\033]PA85C597"        # green

printf "\033]P3C1AEEC"       # darkyellow
printf "\033]PBC7B579"       # yellow

printf "\033]P4A7BF81"       # darkblue
printf "\033]PC73C1EB"        # blue

printf "\033]P568C8B5"         # darkmagenta
printf "\033]PDDFA4D6"      # magenta

clear