#! /bin/dash

printf '\033[?47t'                      # toggle screen buffer
printf '\033[2J'                        # clear screen

printf '\033]11;rgb:FD/F6/E7\007'     # background
printf '\033]708;rgb:FD/F6/E7\007'    # border
printf '\033]10;rgb:71/75/7F\007'     # foreground
printf '\033]706;rgb:4E/50/5A\007'  # bold
printf '\033]704;rgb:4E/50/5A\007'  # italic
printf '\033]707;rgb:4E/50/5A\007'  # underline
printf '\033]12;rgb:00/7C/99\007'           # cursor

printf '\033]4;0;rgb:FD/F6/E7\007'    # black
printf '\033]4;8;rgb:99/9B/A6\007'    # darkgrey

printf '\033]4;7;rgb:71/75/7F\007'    # lightgrey
printf '\033]4;15;rgb:4E/50/5A\007' # white

printf '\033]4;1;rgb:A0/4F/00\007'        # darkred
printf '\033]4;9;rgb:B9/32/36\007'           # red

printf '\033]4;3;rgb:6F/55/C2\007'        # darkyellow
printf '\033]4;11;rgb:77/65/00\007'       # yellow

printf '\033]4;2;rgb:BD/21/69\007'          # darkgreen
printf '\033]4;10;rgb:00/7A/2C\007'        # green

printf '\033]4;6;rgb:EA/E5/D6\007'       # darkcyan
printf '\033]4;14;rgb:00/7C/99\007'         # cyan

printf '\033]4;4;rgb:3F/73/00\007'        # darkblue
printf '\033]4;12;rgb:00/77/C1\007'        # blue

printf '\033]4;5;rgb:00/7D/64\007'          # darkmagenta
printf '\033]4;13;rgb:A6/37/9C\007'      # magenta

printf '\033[?47t'                      # toggle screen buffer