#! /bin/dash

printf '\033[?47t'                      # toggle screen buffer
printf '\033[2J'                        # clear screen

printf '\033]11;rgb:FD/F6/E7\007'     # background
printf '\033]708;rgb:FD/F6/E7\007'    # border
printf '\033]10;rgb:71/75/7F\007'     # foreground
printf '\033]706;rgb:4E/50/5A\007'  # bold
printf '\033]704;rgb:4E/50/5A\007'  # italic
printf '\033]707;rgb:4E/50/5A\007'  # underline
printf '\033]12;rgb:00/8C/A9\007'           # cursor

printf '\033]4;0;rgb:FD/F6/E7\007'    # black
printf '\033]4;8;rgb:99/9B/A6\007'    # darkgrey

printf '\033]4;7;rgb:71/75/7F\007'    # lightgrey
printf '\033]4;15;rgb:4E/50/5A\007' # white

printf '\033]4;1;rgb:B1/5D/0E\007'        # darkred
printf '\033]4;9;rgb:CB/43/44\007'           # red

printf '\033]4;3;rgb:80/63/D3\007'        # darkyellow
printf '\033]4;11;rgb:87/74/00\007'       # yellow

printf '\033]4;2;rgb:CF/37/78\007'          # darkgreen
printf '\033]4;10;rgb:00/8A/3A\007'        # green

printf '\033]4;6;rgb:EA/E5/D6\007'       # darkcyan
printf '\033]4;14;rgb:00/8C/A9\007'         # cyan

printf '\033]4;4;rgb:4F/82/00\007'        # darkblue
printf '\033]4;12;rgb:00/86/D2\007'        # blue

printf '\033]4;5;rgb:00/8D/73\007'          # darkmagenta
printf '\033]4;13;rgb:B7/48/AC\007'      # magenta

printf '\033[?47t'                      # toggle screen buffer