#! /bin/dash

printf '\033[?47t'                      # toggle screen buffer
printf '\033[2J'                        # clear screen

printf '\033]11;rgb:32/31/2E\007'     # background
printf '\033]708;rgb:32/31/2E\007'    # border
printf '\033]10;rgb:A4/A6/B1\007'     # foreground
printf '\033]706;rgb:CE/CF/DB\007'  # bold
printf '\033]704;rgb:CE/CF/DB\007'  # italic
printf '\033]707;rgb:CE/CF/DB\007'  # underline
printf '\033]12;rgb:5E/C6/D4\007'           # cursor

printf '\033]4;0;rgb:32/31/2E\007'    # black
printf '\033]4;8;rgb:7E/7F/89\007'    # darkgrey

printf '\033]4;7;rgb:A4/A6/B1\007'    # lightgrey
printf '\033]4;15;rgb:CE/CF/DB\007' # white

printf '\033]4;1;rgb:E0/AB/83\007'        # darkred
printf '\033]4;9;rgb:EF/A2/9A\007'           # red

printf '\033]4;3;rgb:C1/AE/EC\007'        # darkyellow
printf '\033]4;11;rgb:C7/B5/79\007'       # yellow

printf '\033]4;2;rgb:EF/9F/B8\007'          # darkgreen
printf '\033]4;10;rgb:85/C5/97\007'        # green

printf '\033]4;6;rgb:3F/3E/3B\007'       # darkcyan
printf '\033]4;14;rgb:5E/C6/D4\007'         # cyan

printf '\033]4;4;rgb:A7/BF/81\007'        # darkblue
printf '\033]4;12;rgb:73/C1/EB\007'        # blue

printf '\033]4;5;rgb:68/C8/B5\007'          # darkmagenta
printf '\033]4;13;rgb:DF/A4/D6\007'      # magenta

printf '\033[?47t'                      # toggle screen buffer