#! /bin/dash

printf "\033]P0FDF6E7"   # black
printf "\033]P8999BA6"   # darkgrey

printf "\033]P771757F"   # lightgrey
printf "\033]PF4E505A" # white

printf "\033]P6EAE5D6"      # darkcyan
printf "\033]PE007C99"         # cyan

printf "\033]P1A04F00"       # darkred
printf "\033]P9B93236"          # red

printf "\033]P2BD2169"         # darkgreen
printf "\033]PA007A2C"        # green

printf "\033]P36F55C2"       # darkyellow
printf "\033]PB776500"       # yellow

printf "\033]P43F7300"       # darkblue
printf "\033]PC0077C1"        # blue

printf "\033]P5007D64"         # darkmagenta
printf "\033]PDA6379C"      # magenta

clear