#! /bin/dash

printf "\033]P02E2C28"   # black
printf "\033]P86F7277"   # dark grey

printf "\033]P7A3A6AB"   # light grey
printf "\033]PFF6F9FF"      # white

printf "\033]P6009BAA"     # dark cyan
printf "\033]PE42CAD9"         # cyan

printf "\033]P1C7756E"      # dark red
printf "\033]P9F9A299"          # red

printf "\033]P259996B"    # dark green
printf "\033]PA85C796"        # green

printf "\033]P39F8A4B"   # dark yellow
printf "\033]PBCFB776"       # yellow

printf "\033]P45B8FCA"     # dark blue
printf "\033]PC8BBCFA"         # blue

printf "\033]P5B378AB"  # dark magenta
printf "\033]PDE3A5DA"      # magenta

clear