#! /bin/dash

printf "\033]P0FFF9EC"   # black
printf "\033]P89FA6B2"   # dark grey

printf "\033]P76C727E"   # light grey
printf "\033]PF262C36"      # white

printf "\033]P600A4C1"     # dark cyan
printf "\033]PE007793"         # cyan

printf "\033]P1EA5C58"      # dark red
printf "\033]P9B52C30"          # red

printf "\033]P200A151"    # dark green
printf "\033]PA007328"        # green

printf "\033]P3A68900"   # dark yellow
printf "\033]PB765F00"       # yellow

printf "\033]P40092FA"     # dark blue
printf "\033]PC0067C9"         # blue

printf "\033]P5CD63C3"  # dark magenta
printf "\033]PD9D3595"      # magenta

clear